### ISSUE TITLE
Dome 柱状图奔溃

### ISSUE THREAD

**Issue by lxn1445663013** [openXu/OXChart#26]
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.RectF.left' on a null object reference
        at com.openxu.cview.chart.barchart.BarVerticalChart.evaluatorByData(BarVerticalChart.java:150)
        at com.openxu.cview.chart.barchart.BarVerticalChart.onMeasure(BarVerticalChart.java:127)
        at android.view.View.measure(View.java:25029)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25029)
        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1414)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.widget.ScrollView.onMeasure(ScrollView.java:452)
        at android.view.View.measure(View.java:25029)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25029)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:25029)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25029)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25029)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25029)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6968)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:775)
        at android.view.View.measure(View.java:25029)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3245)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2000)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2305)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1888)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8043)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:969)
        at android.view.Choreographer.doCallbacks(Choreographer.java:793)
        at android.view.Choreographer.doFrame(Choreographer.java:728)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7551)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by Zkp275557625** [comment]
+1

**Comment by Zkp275557625** [comment]
修改BaseChart里面 omMeasure如下
@Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        rectChart = new RectF(getPaddingLeft(),getPaddingTop(),getMeasuredWidth()-getPaddingRight(),
                getMeasuredHeight()-getPaddingBottom());
    }

**Comment by lxn1445663013** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openXu/OXChart"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月7日(星期四) 上午10:39
收件人:&nbsp;"openXu/OXChart"<OXChart@noreply.github.com&gt;;
抄送:&nbsp;"令水剑客"<1445663013@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [openXu/OXChart] Dome 柱状图奔溃 (#26)





 
修改BaseChart里面 omMeasure如下
 @override
 protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
 super.onMeasure(widthMeasureSpec, heightMeasureSpec);
 rectChart = new RectF(getPaddingLeft(),getPaddingTop(),getMeasuredWidth()-getPaddingRight(),
 getMeasuredHeight()-getPaddingBottom());
 }
